name = "minecraft.ashwalker.net"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61797c3f482b3e7c580819692791c7ae0c5dc1e5628f33e72e73f69276a41f93"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.60"
