name = "minecraft.ashwalker.net"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "621dc32105266cd79aa512c809e273526a5fcecde9e339e4a441f42803143251"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.60"
