name = "minecraft.ashwalker.net"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f3e7a893bce71c680e6c59920109f5086b9ef87025f1be2c076e86a40df0913"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.60"
