name = "minecraft.ashwalker.net"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec881da805b4263fced5e4ff3816586bae31c31a9028f6395f2e14c866bc17fa"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.65"
