name = "minecraft.ashwalker.net"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4df1241242c166572abf3f2f0b94a9a0a64f90c09c4e94b4e49cca9b1d575dfa"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.60"
