name = "minecraft.ashwalker.net"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ba4305dfc6625c0e74c01c343680322b97678df58798b221275bb2dc2e237a5"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.60"
