hash-format = "sha256"

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "e5bbc96d6d5d6bffb8e36c89bbd1331d923e23fbb87be8bae208d206832adb1c"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "8f7e28eb56a3f538cf2be43c03aea1c5b3017a5fe0429a6b67b052e0f6c0b5d4"
metafile = true
