name = "Drifting League"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4f952542e96d04720e941921f3ac8a32a5c6ba3fb12ac248e1947c477d34958"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4"
