name = "Drifting League"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff278a865a3e678b1d76079ab627272640c453b70c29a66b1641046e207fc60e"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4"
