name = "Drifting League"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e551de4649cf528e853c0b66e6dc7afc827b68b773a45b39941f6fcd0d291358"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4"
