name = "Drifting League"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71c16749551c908f89b8c0b09124dae8a77f8f42e4acc4d5392353393092050c"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4"
