name = "Playground"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac746479761cb0dd0ed0fa932e5b7cd503aa89e9f68b5d4c9496c32ed211f0e7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
