name = "Drifting League"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c752e186b166c7e70926b4bed2065a978bf7e42bb8e4e37ec9bb9df9a495f11"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4"
