name = "Drifting League"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e99fa80884e07e5d3664bcede788264d85ba5bbe828ca22f586696b50166bf23"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4"
