name = "Drifting League"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02f03cfa4bccb1f9303bf768b5cfe579dacf949ce8f0cb900c9ef339ef05db6f"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4"
