name = "Drifting League"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cf6219334b836e0b8b6ac02890ac9e2a58e0c01d95316a343b29df4e1a5deeb"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4"
