name = "Drifting League"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1a8084302b0d2531f245345543cb51fb61cd41283211279cc57093cdcecb1e8"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0-beta.3"
