name = "Drifting League"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a86c44756e123cebccb88cbd006bb78db20557e6cbb664c347de0b11b218849"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4"
