name = "Playground"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5b672458fffe4470a6197ca42fce0c8bf8975c0ce0c5cb94de79067ec1ea1aa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"
