name = "Drifting League"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f551223ba678baf48b24347b55385615776a1095154eb50ead49611fdd1cc22"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4"
