name = "Drifting League"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10d5d1d5eb251d054998a7d0b1cdb9e0fcc58e10c5d38031330278f1271a63cb"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4"
