name = "Drifting League"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1e3b5962ca5cab30a3a8485d05c160767339c30f8451b9a1710fd2a836b36f5"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0-beta.3"
