name = "Drifting League"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13ef301e06012d1e17895a86ea804db3c1a3992cec93c4f8ae9d6ee21785b9b3"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0-beta.3"
