name = "Drifting League"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab434261b1e0bc551d71ad36faadb4b268a845751ce7410b3e9c6fb3bb43fdfa"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4"
