name = "Drifting League"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5de5367aa47a329ba537cafa8443d77f854400df9a4e9bbb3fda8f36931d913c"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4"
