name = "Drifting League"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29de780706faca4e53ef25317828b86cf1bb588b5b91c73bcf1526494cb9eb51"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0-beta.3"
