name = "Drifting League"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef6770dab7a7be9105731df2e47a8704ceb5d755fb9c6fbdbb76e349c29bd074"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4"
