name = "Drifting League"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95ea7f5f2a80dfc422cab2224730723a9d4eccd1ec29cf244869a88ea3cafa26"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0-beta.3"
