name = "Drifting League"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c324f4571651d657f27b480f71cf9721ce44359cc28f9324e8ea38efbae0956b"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0-beta.3"
