name = "Playground"
author = "Ash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8083c473d1f47b97277fd33262e5a65de472500bdf291b7c817d89b3cf238c04"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
